name: CD to Dev

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  # I am using one step to build and deploy. GitHub's extreme limitation on Action uses forced me to do this
  # without an artifact
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
      
    steps:
      - uses: actions/checkout@v4

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y.%m.%d')"

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: npm install, build, and test
        working-directory: ./src
        run: |
          npm install --production
          npm version ${{ steps.date.outputs.date }}
          npm run build --if-present
      
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'paulovtarkovnodejsapi-dev'
          slot-name: 'Production'
          package: ./src
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_6F46A79FD5784D56BC28447C7765468B }}
